const Sdata = {
  shopItems: [
    {
      id: 1,
      cover: "./images/shops/Scandal jean paul gaultier.jpg",
      name: "SCANDAL JEAN PAUL GAULTIER 100ml",
      price: "250",
      discount: "50",
    },
    {
      id: 2,
      cover: "./images/shops/Apa de Toaleta Thierry Mugler.jpg",
      name: "THIERRY MUGLER, ALIEN,\n Apă de Toaleta  Bărbați, 100 ml",
      price: "129",
      discount: "50",
    },
    {
      id: 3,
      cover: "./images/shops/Lacomelavieestbelle.jpg",
      name: "LACOME LA VIE  EST BELLE Femei 100ml",
      price: "250",
      discount: "50 ",
    },
    {
      id: 4,
      cover: "./images/shops/Coco chanel nr 5.webp",
      name: "COCO CHANEL NR 5 Femei 100ml",
      price: "450",
      discount: "50 ",
    },
    {
      id: 5,
      cover: "./images/shops/Coco chanel mademoaselle.jpg",
      name: "COCO CHANEL MADEMOASELLE Femei 100ml",
      price: "410",
      discount: " 50 ",
    },
    {
      id: 6,
      cover: "./images/shops/Cristian dior hipnotic poison.jpg",
      name: "CRISTIAN DIOR HIPNOTIC poison Femei 100ml",
      price: "220",
      discount: " 50",
    },
    {
      id: 7,
      cover: "./images/shops/Apa de parfum Givenchy L'Interdit.webp",
      name: " GIVENCHY L'INTERDIT \n Apă de parfum, 80 ml, pentru femei",
      price: "200",
      discount: "50 ",
    },
    {
      id: 8,
      cover: "./images/shops/PACO RABANNE OLYMPÉA.jpg",
      name: "PACO RABANNE OLYMPÉA\n" +
          "Apă de parfum pentru femei 80 ml",
      price: "180",
      discount: "50",
    },
    {
      id: 9,
      cover: "./images/shops/Coco chanel mademoiselle intense.jpg",
      name: "CHANEL COCO MADEMOISELLE INTENSE\n" +
          "Apă de parfum pentru femei 100 ml",
      price: "410",
      discount: "50",
    },
    {
      id: 10,
      cover: "./images/shops/Giorgio armani my way.webp",
      name: "GIORGIO ARMANI MY WAY\n " +
          "Eau de Parfum reincarcabil pentru femei 90 ml",
      price: "300",
      discount: "50",
    },
    {
      id: 11,
      cover: "./images/shops/Armani Si Intense.webp",
      name: "GIORGIO ARMANI\n" +
          "Apă de parfum Giorgio Armani Si Intense 2021, 100 ml, pentru femei",
      price: "370",
      discount: "50",
    },
    {
      id: 12,
      cover: "./images/shops/Coco Chanele change eau tendre.jpg",
      name: "CHANCE EAU TENDRE\n" +
          "Eau de Toilette pentru femei 100 ml",
      price: "450",
      discount: "50",
    },
    {
      id: 13,
      cover: "./images/shops/Lacome idole.jpg",
      name: "LANCÔME IDÔLE\n" +
          "Apă de parfum pentru femei 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 14,
      cover: "./images/shops/Caroljna herera good girl Velvet fatale.jpg",
      name: "CAROLINA HERRERA VERY GOOD GIRL\n" +
          "Apă de parfum pentru femei 80 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 15,
      cover: "./images/shops/Dolce gabana the one.jpg",
      name: "DOLCE&GABBANA THE ONE FOR MEN\n" +
          "Apă de toaletă pentru bărbați 100 ml",
      price: "200",
      discount: "50",
    },
    {
      id: 16,
      cover: "./images/shops/Cristian dior Mis dior Chery.webp",
      name: "CHRISTIAN DIOR Miss Dior Rose N`Roses\n Apă de toaleta , Femei, 100ml",
      price: "300",
      discount: "50",
    },
    {
      id: 17,
      cover: "./images/shops/Lacome Poeme.jpg",
      name: "LACOME POEME Apă de Parfum, Femei, 100ml",
      price: "250",
      discount: "50",
    },
    {
      id: 18,
      cover: "./images/shops/Maison francis kurkadjian.jpg",
      name: "MAISON FRANCIS KURKDJIAN BACCARAT ROUGE 540\n,Femei Parfum 70 ml",
      price: "900",
      discount: "50",
    },
    {
      id: 19,
      cover: "./images/shops/Tom ford lost chery.jpg",
      name: "TOM FORD LOST CHERRY| Obsentum \n,Femei, 100ml",
      price: "900",
      discount: "50",
    },
    {
      id: 20,
      cover: "./images/shops/Tom ford bitter peach.jpg",
      name: "TOM FORD BITTER PEACH\n,Femei, 100ml",
      price: "1000",
      discount: "50",
    },
    {
      id: 21,
      cover: "./images/shops/Carolina herera good girl.jpg",
      name: "CAROLINA HERRERA GOOD GIRL \n,Apă de parfum pentru femei 80 ml",
      price: "300",
      discount: "50",
    },
    {
      id: 22,
      cover: "./images/shops/Dolce gabbana the one.png",
      name: "DOLCE GABBANA THE ONE \n,Bărbați 100 ml",
      price: "200",
      discount: "50",
    },
    {
      id: 23,
      cover: "./images/shops/Scandal jean paul femei.jpg",
      name: "SCANDAL JEAN PAUL\n,Femei 80 ml",
      price: "200",
      discount: "50",
    },
    {
      id: 24,
      cover: "./images/shops/GIORGIO ARMANI ACQUA DI GIÒ POUR HOMME.jpg",
      name: "GIORGIO ARMANI ACQUA DI GIÒ POUR HOMME\n,Apă de toaletă pentru bărbați 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 25,
      cover: "./images/shops/Dior Sovage elixir.jpg",
      name: "CHRISTIAN DIOR SAUVAGE ELIXIR\n,Parfum pentru bărbați 60 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 26,
      cover: "./images/shops/TOM FORD NOIR.jpg",
      name: "TOM FORD NOIR\n,Parfum pentru bărbați 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 27,
      cover: "./images/shops/TOM FORD NOIR EXTRIME.jpg",
      name: "TOM FORD NOIR EXTREME\n,Parfum pentru bărbați 100 ml",
      price: "400",
      discount: "50",
    },
    {
      id: 28,
      cover: "./images/shops/PACO ROBANE INVICTUS LEGEND.jpg",
      name: "PACO RABANNE  INVICTUS LEGEND\n,Parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 29,
      cover: "./images/shops/PACO RABANNE INVICTUS VICTORY.jpg",
      name: "PACO RABANNE INVICTUS VICTORY\n,Apă de parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 30,
      cover: "./images/shops/Paco robane pure xs.jpg",
      name: "PACO ROBANE PURE XS\n,Apă de parfum pentru bărbați 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 31,
      cover: "./images/shops/DIOR SOVAGE.jpg",
      name: "CHRISTIAN DIOR SAUVAGE\n,Parfum pentru bărbați 100 ml",
      price: "400",
      discount: "50",
    },
    {
      id: 32,
      cover: "./images/shops/Dior sovage Apa de parfum.webp",
      name: "DIOR SAUVAGE\n,Sauvage Eau de Parfum de la Dior este un parfum masculin 100 ml",
      price: "400",
      discount: "50",
    },
    {
      id: 33,
      cover: "./images/shops/DIOR HOME INTENS.webp",
      name: "DIOR HOME INTENS\n,Apă de parfum pentru bărbați 100 ml",
      price: "400",
      discount: "50",
    },
    {
      id: 34,
      cover: "./images/shops/Armani strong You.jpg",
      name: "ARMANI STRONGER YOU\n,Apă de parfum pentru bărbați 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 35,
      cover: "./images/shops/Paco robane milion prive.webp",
      name: "PACO RABANNE MILLION PRIVE\n,Apă de parfum pentru bărbați 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 36,
      cover: "./images/shops/Tom ford ombre leather.jpg",
      name: "TOM FORD OMBRE LEATHER\n,Apă de parfum pentru bărbați 100 ml",
      price: "250",
      discount: "50",
    },
    {
      id: 37,
      cover: "./images/shops/Tom ford ombre leather.jpg",
      name: "TOM FORD OMBRÉ LEATHER\n,Apă de parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 38,
      cover: "./images/shops/Armani black cod.webp",
      name: "ARMANI BLACK COD\n,Parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 39,
      cover: "./images/shops/Armani code parfumo.jpg",
      name: "ARMANI CODE PARFUMO\n,Parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 40,
      cover: "./images/shops/Boss de scient.jpg",
      name: "BOSS DE SCIENT\n,Apă de parfum pentru bărbați 100 ml",
      price: "200",
      discount: "50",
    },
    {
      id: 41,
      cover: "./images/shops/Bulgari mqn in black.jpg",
      name: "BVLGARI MAN IN BLACK\n,Parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 42,
      cover: "./images/shops/Tom ford out wod.jpg",
      name: "TOM FORD OUT WOD\n,Apă de parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 43,
      cover: "./images/shops/tom ford tobacco vanille.jpg",
      name: "TOM FORD TOBACCO VANILLE\n,Apă de parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
    {
      id: 44,
      cover: "./images/shops/tom ford tobacco vanille.jpg",
      name: "TOM FORD TOBACCO VANILLE\n,Apă de parfum pentru bărbați 100 ml",
      price: "350",
      discount: "50",
    },
  ],
}
export default Sdata




