const Sdata = {
    shopItems: [
        {
            id: 1,
            cover: "./images/shops/Scandal jean paul gaultier.jpg",
            name: "Jean Paul Gaultier Scandal Pour Homme  Apă de Toaleta  Bărbați, 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 2,
            cover: "./images/shops/Dior sovage Apa de parfum.webp",
            name: "Dior Sauvage – Eau de Parfum, 100ml Barbati",
            price: "275",
            discount: "50",
        },
        {
            id: 3,
            cover: "./images/shops/Creed Aventus.jpg",
            name: "Creed Aventus – Eau de Parfum, 100ml Barbati",
            price: "500",
            discount: "50",
        },
        {
            id: 4,
            cover: "./images/shops/Chanel Bleu de Chanell.jpg",
            name: "Chanel Bleu de Chanel – Eau de Parfum, 100ml Barbati",
            price: "325",
            discount: "50",
        },
        {
            id: 5,
            cover: "./images/shops/Apa de Toaleta Thierry Mugler.jpg",
            name: "THIERRY MUGLER ALIEN,\n Apă de Toaleta  Femei, 90 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 6,
            cover: "./images/shops/Lacomelavieestbelle.jpg",
            name: "LACOME LA VIE  EST BELLE Femei 100ml",
            price: "250",
            discount: "50 ",
        },
        {
            id: 7,
            cover: "./images/shops/Coco chanel nr 5.webp",
            name: "COCO CHANEL NR 5 Femei 100ml",
            price: "450",
            discount: "50 ",
        },
        {
            id: 8,
            cover: "./images/shops/Coco chanel mademoaselle.jpg",
            name: "COCO CHANEL MADEMOASELLE Femei 100ml",
            price: "410",
            discount: " 50 ",
        },
        {
            id: 9,
            cover: "./images/shops/Cristian dior hipnotic poison.jpg",
            name: "Christian Dior Hypnotic Poison \n Apă de parfum Femei 100ml",
            price: "250",
            discount: " 50",
        },
        {
            id: 10,
            cover: "./images/shops/Apa de parfum Givenchy L'Interdit.webp",
            name: " GIVENCHY L'INTERDIT \n Apă de parfum 80 ml, pentru femei",
            price: "300",
            discount: "50 ",
        },
        {
            id: 11,
            cover: "./images/shops/PACO RABANNE OLYMPÉA.jpg",
            name: "PACO RABANNE OLYMPÉA\n" +
                "Apă de parfum pentru femei 80 ml",
            price: "180",
            discount: "50",
        },
        {
            id: 12,
            cover: "./images/shops/Coco chanel mademoiselle intense.jpg",
            name: "CHANEL COCO MADEMOISELLE INTENSE\n" +
                "Apă de parfum pentru femei 100 ml",
            price: "350",
            discount: "50",
        },
        {
            id: 13,
            cover: "./images/shops/Giorgio armani my way.webp",
            name: "GIORGIO ARMANI MY WAY\n " +
                "Eau de Parfum reincarcabil pentru femei 90 ml",
            price: "260",
            discount: "50",
        },
        {
            id: 14,
            cover: "./images/shops/Armani Si.webp",
            name: "GIORGIO ARMANI\n" +
                "Armani Si, 100 ml, pentru femei",
            price: "240",
            discount: "50",
        },
        {
            id: 15,
            cover: "./images/shops/Coco Chanele change eau tendre.jpg",
            name: "CHANCE EAU TENDRE\n" +
                "Eau de Toilette pentru femei 100 ml",
            price: "450",
            discount: "50",
        },
        {
            id: 16,
            cover: "./images/shops/LANCÔME IDÔLE.webp",
            name: "LANCÔME IDÔLE\n" +
                "Apă de parfum pentru femei 75 ml",
            price: "220",
            discount: "50",
        },
        {
            id: 17,
            cover: "./images/shops/Caroljna herera good girl Velvet fatale.jpg",
            name: "CAROLINA HERRERA VERY GOOD GIRL\n" +
                "Apă de parfum pentru femei 80 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 18,
            cover: "./images/shops/Dolce gabana the one.jpg",
            name: "DOLCE&GABBANA THE ONE FOR MEN\n" +
                "Apă de toaletă pentru bărbați 100 ml",
            price: "200",
            discount: "50",
        },
        {
            id: 19,
            cover: "./images/shops/Cristian dior Mis dior Chery.webp",
            name: "CHRISTIAN DIOR Miss Dior Rose N`Roses\n Apă de toaleta , Femei, 100ml",
            price: "300",
            discount: "50",
        },
        {
            id: 20,
            cover: "./images/shops/Lacome Poeme.jpg",
            name: "LACOME POEME Apă de Parfum, Femei, 100ml",
            price: "250",
            discount: "50",
        },
        {
            id: 21,
            cover: "./images/shops/Maison francis kurkadjian.jpg",
            name: "MAISON FRANCIS KURKDJIAN BACCARAT ROUGE 540\n,Femei Parfum 70 ml",
            price: "900",
            discount: "50",
        },
        {
            id: 22,
            cover: "./images/shops/Tom ford lost chery.jpg",
            name: "TOM FORD LOST CHERRY| Obsentum \n,Femei, 100ml",
            price: "900",
            discount: "50",
        },
        {
            id: 23,
            cover: "./images/shops/Tom ford bitter peach.jpg",
            name: "TOM FORD BITTER PEACH\n,Femei, 100ml",
            price: "1000",
            discount: "50",
        },
        {
            id: 24,
            cover: "./images/shops/Carolina herera good girl.jpg",
            name: "CAROLINA HERRERA GOOD GIRL \n,Apă de parfum pentru femei 80 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 25,
            cover: "./images/shops/Dolce gabbana the one.png",
            name: "DOLCE GABBANA THE ONE \n,Bărbați 100 ml",
            price: "200",
            discount: "50",
        },
        {
            id: 26,
            cover: "./images/shops/Scandal jean paul femei.jpg",
            name: "SCANDAL JEAN PAUL\n,Femei 80 ml",
            price: "200",
            discount: "50",
        },
        {
            id: 27,
            cover: "./images/shops/GIORGIO ARMANI ACQUA DI GIÒ POUR HOMME.jpg",
            name: "GIORGIO ARMANI ACQUA DI GIÒ POUR HOMME\n,Apă de toaletă pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 28,
            cover: "./images/shops/Dior Sovage elixir.jpg",
            name: "CHRISTIAN DIOR SAUVAGE ELIXIR\n,Parfum pentru bărbați 60 ml",
            price: "325",
            discount: "50",
        },
        {
            id: 29,
            cover: "./images/shops/TOM FORD NOIR.jpg",
            name: "TOM FORD NOIR (black)\n,Parfum pentru bărbați 100 ml",
            price: "280",
            discount: "50",
        },
        {
            id: 30,
            cover: "./images/shops/TOM FORD NOIR EXTRIME.jpg",
            name: "TOM FORD NOIR EXTREME(gold)\n,Parfum pentru bărbați 100 ml",
            price: "280",
            discount: "50",
        },
        {
            id: 31,
            cover: "./images/shops/PACO ROBANE INVICTUS LEGEND.jpg",
            name: "Paco Rabanne Invictus Legend\n,Parfum pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 32,
            cover: "./images/shops/PACO RABANNE INVICTUS VICTORY.jpg",
            name: "Paco Rabanne Invictus Victory\n,Apă de parfum pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 33,
            cover: "./images/shops/Paco robane pure xs.jpg",
            name: "PACO ROBANE PURE XS\n,Apă de parfum pentru bărbați 100 ml",
            price: "220",
            discount: "50",
        },
        {
            id: 34,
            cover: "./images/shops/DIOR SOVAGE.jpg",
            name: "CHRISTIAN DIOR SAUVAGE\n,Parfum pentru bărbați 100 ml",
            price: "350",
            discount: "50",
        },

        {
            id: 35,
            cover: "./images/shops/DIOR HOME INTENS.webp",
            name: "Dior Homme Intense\n,Apă de parfum pentru bărbați 100 ml",
            price: "260",
            discount: "50",
        },
        {
            id: 36,
            cover: "./images/shops/Armani strong You.jpg",
            name: "Armani Stronger with you Absolutely\n,Apă de parfum pentru bărbați 100 ml",
            price: "260",
            discount: "50",
        },
        {
            id: 37,
            cover: "./images/shops/Paco robane milion prive.webp",
            name: "PACO RABANNE MILLION PRIVE\n,Apă de parfum pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 39,
            cover: "./images/shops/Tom ford ombre leather.jpg",
            name: "TOM FORD OMBRÉ LEATHER\n,Apă de parfum pentru bărbați 100 ml",
            price: "350",
            discount: "50",
        },
        {
            id: 40,
            cover: "./images/shops/Armani black cod.webp",
            name: "ARMANI BLACK COD\n,Parfum pentru bărbați 100 ml",
            price: "350",
            discount: "50",
        },
        {
            id: 41,
            cover: "./images/shops/Armani code parfumo.jpg",
            name: "ARMANI CODE PARFUMO\n,Parfum pentru bărbați 100 ml",
            price: "290",
            discount: "50",
        },
        {
            id: 42,
            cover: "./images/shops/Boss de scient.jpg",
            name: "BOSS DE SCIENT\n,Apă de parfum pentru bărbați 100 ml",
            price: "200",
            discount: "50",
        },
        {
            id: 43,
            cover: "./images/shops/Bulgari mqn in black.jpg",
            name: "BVLGARI MAN IN BLACK\n,Parfum pentru bărbați 100 ml",
            price: "300",
            discount: "50",
        },
        {
            id: 44,
            cover: "./images/shops/Tom ford out wod.jpg",
            name: "TOM FORD OUT WOD\n,Apă de parfum pentru bărbați 100 ml",
            price: "350",
            discount: "50",
        },
        {
            id: 45,
            cover: "./images/shops/tom ford tobacco vanille.jpg",
            name: "TOM FORD TOBACCO VANILLE\n,Apă de parfum pentru bărbați 100 ml",
            price: "600",
            discount: "50",
        },
        {
            id: 46,
            cover: "./images/shops/Tom Ford, Vanille Fatale.jpg",
            name: "Tom Ford, Vanille Fatale\n,Apă de parfum pentru bărbați 100 ml",
            price: "500",
            discount: "50",
        },
        {
            id: 47,
            cover: "./images/shops/Tom Ford Japon Noir.jpg",
            name: "Tom Ford Japon Noir\n,Apă de parfum pentru bărbați 100 ml",
            price: "400",
            discount: "50",
        },
        {
            id: 48,
            cover: "./images/shops/Tom Ford Tobacco Oud.jpg",
            name: "Tom Ford Tobacco Oud\n,Apă de parfum pentru bărbați 100 ml",
            price: "600",
            discount: "50",
        },
        {
            id: 49,
            cover: "./images/shops/Tom Ford Fucking Fabulous.webp",
            name: "Tom Ford Fucking Fabulous\n,Apă de parfum pentru bărbați 100 ml",
            price: "500",
            discount: "50",
        },

        {
            id: 51,
            cover: "./images/shops/Paco Rabanne Phantom.jpg",
            name: "Paco Rabanne Phantom\n,Apă de parfum pentru bărbați 100 ml",
            price: "275",
            discount: "50",
        },
        {
            id: 52,
            cover: "./images/shops/Dior Fahrenheit.jpg",
            name: "Dior Fahrenheit\n,Apă de parfum pentru bărbați 100 ml",
            price: "280",
            discount: "50",
        },
        {
            id: 53,
            cover: "./images/shops/Hermès Terre D’Hermès.jpg",
            name: "Hermès Terre D’Hermès\n,Apă de parfum pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 54,
            cover: "./images/shops/Versace Eros.webp",
            name: "Versace Eros\n,Apă de parfum pentru bărbați 100 ml",
            price: "260",
            discount: "50",
        },
        {
            id: 55,
            cover: "./images/shops/Armani Aqua di Gio Profondo.webp",
            name: "Armani Aqua di Gio Profondo\n,Apă de parfum pentru bărbați 75ml",
            price: "240",
            discount: "50",
        },
        {
            id: 57,
            cover: "./images/shops/Chanel Allure Homme Sport.webp",
            name: "Chanel Allure Homme Sport\n,Apă de parfum pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 58,
            cover: "./images/shops/Jean Paul Gaultier Le Male.jpg",
            name: "Jean Paul Gaultier Le Male\n,Apă de parfum pentru bărbați 125 ml",
            price: "200",
            discount: "50",
        },
        {
            id: 59,
            cover: "./images/shops/Burberry Hero.webp",
            name: "Burberry Hero\n,Apă de parfum pentru bărbați 100 ml",
            price: "220",
            discount: "50",
        },
        {
            id: 60,
            cover: "./images/shops/Wanted Azzaro.webp",
            name: "Wanted Azzaro\n,Apă de parfum pentru bărbați 100 ml",
            price: "190",
            discount: "50",
        },
        {
            id: 61,
            cover: "./images/shops/Creed Aventus 10th Anniversary.jpg",
            name: "Creed Aventus 10th Anniversaryo\n,Apă de parfum pentru bărbați 100 ml",
            price: "450",
            discount: "50",
        },
        {
            id: 62,
            cover: "./images/shops/Givenchi Pi.webp",
            name: "Givenchi Pi\n,Apă de parfum pentru bărbați 100 ml",
            price: "210",
            discount: "50",
        },
        {
            id: 63,
            cover: "./images/shops/Yves Saint Laurent Kouros.webp",
            name: "Yves Saint Laurent Kouros\n,Apă de parfum pentru bărbați 100 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 64,
            cover: "./images/shops/Nasomatto Black Afgano.jpg",
            name: "Nasomatto Black Afgano\n,Extract de Parfum pentru bărbați 30 ml",
            price: "350",
            discount: "50",
        },
        {
            id: 65,
            cover: "./images/shops/Yves Saint Laurent La Nuit de L'Homme.png",
            name: "Yves Saint Laurent La Nuit de L'Homme\n,Extract de Parfum pentru bărbați 100 ml",
            price: "190",
            discount: "50",
        },
        {
            id: 66,
            cover: "./images/shops/Dolce Gabbana Light Blue.webp",
            name: "Dolce Gabbana Light Blue\n,Extract de Parfum pentru bărbați 100 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 67,
            cover: "./images/shops/Azzaro The Most Wanted Eau De Parfum Intense.jpg",
            name: "Azzaro The Most Wanted Eau De Parfum Intense\n,Extract de Parfum pentru bărbați 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 68,
            cover: "./images/shops/Dolce & Gabbana K.jpg",
            name: "Dolce & Gabbana K\n,Extract de Parfum pentru bărbați 100 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 69,
            cover: "./images/shops/Yves Saint Laurent L'Homme Le Parfum.jpg",
            name: "Yves Saint Laurent L'Homme Le Parfum\n,Extract de Parfum pentru bărbați 100 ml",
            price: "280",
            discount: "50",
        },
        {
            id: 70,
            cover: "./images/shops/Yves Saint Laurent Y.webp",
            name: "Yves Saint Laurent Y\n,Extract de Parfum pentru bărbați 100 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 71,
            cover: "./images/shops/Bvlgari Aqva Pour Homme.jpg",
            name: "Bvlgari Aqva Pour Homme\n,Extract de Parfum pentru bărbați 100 ml",
            price: "190",
            discount: "50",
        },
        {
            id: 72,
            cover: "./images/shops/Yves Saint Laurent Black Opium.jpg",
            name: "Yves Saint Laurent Black Opium\n,Extract de Parfum pentru femei 90 ml",
            price: "210",
            discount: "50",
        },
        {
            id: 73,
            cover: "./images/shops/Jean Paul Gaultier Scandal by Night.jpg",
            name: "Jean Paul Gaultier Scandal by Night\n,Apa de Parfum pentru femei 80 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 74,
            cover: "./images/shops/Yves Saint Laurent Libre.webp",
            name: "Yves Saint Laurent Libre\n,Apa de Parfum pentru femei 90 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 75,
            cover: "./images/shops/Armani Si Passione.webp",
            name: "Armani Si Passione\n,Apa de Parfum pentru femei 100 ml",
            price: "250",
            discount: "50",
        }
        ,
        {
            id: 76,
            cover: "./images/shops/Versace Crystal Noir.webp",
            name: "Versace Crystal Noir\n,Apa de Parfum pentru femei 90 ml",
            price: "200",
            discount: "50",
        }
        ,
        {
            id: 77,
            cover: "./images/shops/Xerjoff Muse.jpg",
            name: "Xerjoff Muse\n,Apa de Parfum pentru femei 100 ml",
            price: "450",
            discount: "50",
        },
        {
            id: 78,
            cover: "./images/shops/Christian Dior J’Adore.webp",
            name: "Christian Dior J’Adore\n,Apa de Parfum pentru femei 100 ml",
            price: "250",
            discount: "50",
        },
        {
            id: 79,
            cover: "./images/shops/Christian Dior Addict.jpg",
            name: "Christian Dior Addict\n,Apa de Parfum pentru femei 100 ml",
            price: "280",
            discount: "50",
        }
        ,
        {
            id: 80,
            cover: "./images/shops/Armani Stronger With You Intensely.webp",
            name: "Armani Stronger With You Intensely\n,Apa de Parfum pentru femei 100 ml",
            price: "250",
            discount: "50",
        }
        ,
        {
            id: 81,
            cover: "./images/shops/Armani Because It’s You.jpg",
            name: "Armani Because It’s You\n,Apa de Parfum pentru femei 100 ml",
            price: "250",
            discount: "50",
        }
        ,
        {
            id: 82,
            cover: "./images/shops/Paco Rabanne Olympeea.webp",
            name: "Paco Rabanne Olympeea\n,Apa de Parfum pentru femei 80 ml",
            price: "200",
            discount: "50",
        }
        ,
        {
            id: 83,
            cover: "./images/shops/Giorgio Armani My Way Intense.jpg",
            name: "Giorgio Armani My Way Intense\n,Apa de Parfum pentru femei 90 ml",
            price: "350",
            discount: "50",
        }
        ,
        {
            id: 84,
            cover: "./images/shops/Prada Candy.webp",
            name: "Prada Candy\n,Apa de Parfum pentru femei 80 ml",
            price: "220",
            discount: "50",
        }
        ,
        {
            id: 85,
            cover: "./images/shops/Xerjoff Casamorati 1888 Lira.jpg",
            name: "Xerjoff Casamorati 1888 Lira\n,Apa de Parfum pentru femei 100 ml",
            price: "550",
            discount: "50",
        }
        ,
        {
            id: 86,
            cover: "./images/shops/Tom Ford Velvet Orchid.webp",
            name: "Tom Ford Velvet Orchid\n,Apa de Parfum pentru femei 100 ml",
            price: "290",
            discount: "50",
        }
        ,
        {
            id: 87,
            cover: "./images/shops/L' Interdit Intense Givenchy.webp",
            name: "L' Interdit Intense Givenchy\n,Apa de Parfum pentru femei 80 ml",
            price: "260",
            discount: "50",
        }
        ,
        {
            id: 88,
            cover: "./images/shops/Dior JOY.webp",
            name: "Dior JOY\n,Apa de Parfum pentru femei 90 ml",
            price: "380",
            discount: "50",
        }
        ,
        {
            id: 89,
            cover: "./images/shops/Coco Chanel Chance.webp",
            name: "Coco Chanel Chance\n,Apa de Parfum pentru femei 100 ml",
            price: "380",
            discount: "50",
        }
        ,
        {
            id: 90,
            cover: "./images/shops/Xerjoff Wardasina.jpg",
            name: "Xerjoff Wardasina\n,Apa de Parfum pentru femei 100 ml",
            price: "600",
            discount: "50",
        },
        {
            id: 91,
            cover: "./images/shops/Givenchy L'Interdit Rouge.webp",
            name: "Givenchy L'Interdit Rouge\n,Apa de Parfum pentru femei 80 ml",
            price: "200",
            discount: "50",
        },
        {
            id: 92,
            cover: "./images/shops/Montale Roses Musk.jpg",
            name: "Montale Roses Musk\n,Apa de Parfum pentru femei 100 ml",
            price: "240",
            discount: "50",
        },
        {
            id: 93,
            cover: "./images/shops/Tom Ford Metalique.webp",
            name: "Tom Ford Metallique\n,Apa de Parfum pentru femei 100 ml",
            price: "450",
            discount: "50",
        }
        ,
        {
            id: 94,
            cover: "./images/shops/Paco Rabanne Lady Million.jpg",
            name: "Paco Rabanne Lady Million\n,Apa de Parfum pentru femei 80 ml",
            price: "260",
            discount: "50",
        } ,
        {
            id: 95,
            cover: "./images/shops/Narciso Rodriguez for Her.webp",
            name: "Narciso Rodriguez for Her\n,Apa de Parfum pentru femei 100 ml",
            price: "240",
            discount: "50",
        }
        ,
        {
            id: 96,
            cover: "./images/shops/Lancôme HYPNOSE.jpg",
            name: "Lancôme HYPNOSE\n,Apa de Parfum pentru femei 75 ml",
            price: "250",
            discount: "50",
        }
        ,
        {
            id: 97,
            cover: "./images/shops/My Burberry Black.webp",
            name: "My Burberry Black\n,Apa de Parfum pentru femei 90 ml",
            price: "250",
            discount: "50",
        }
    ],
}
export default Sdata




